# Generated by Django 5.0 on 2023-12-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_id', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('status', models.CharField(choices=[('D', 'Danger'), ('S', 'Safe')], max_length=1)),
                ('session_id', models.UUIDField()),
                ('log_type', models.CharField(max_length=10)),
                ('log_coordinates', models.CharField(max_length=100)),
                ('log_thumbnail', models.TextField()),
            ],
        ),
    ]
