# Generated by Django 4.2.8 on 2023-12-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AddField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='this is a image and it is encoded with base64', null=True, upload_to='client/media/', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='event',
            name='log_coordinates',
            field=models.JSONField(default=list, help_text='this field include four list of integer ', verbose_name='log_coordinates'),
        ),
        migrations.AlterField(
            model_name='event',
            name='log_type',
            field=models.CharField(choices=[('P', 'Person'), ('F', 'Face'), ('B', 'Bag')], help_text=' you have to choose one of these for complete an event.', max_length=10, verbose_name='log_type'),
        ),
        migrations.AlterField(
            model_name='event',
            name='session_id',
            field=models.UUIDField(help_text='this is uuid field .', unique=True, verbose_name='session_id'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('D', 'Danger'), ('S', 'Safe')], help_text=' status has two choices: D is for danger event and S is for safe event. ', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='event',
            name='stream_id',
            field=models.IntegerField(help_text='stream id is an integer field ', unique=True, verbose_name='stream_id'),
        ),
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(help_text='data for each event.', verbose_name='timestamp'),
        ),
    ]
