# Generated by Django 4.2.8 on 2023-12-19 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_event_options_event_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='log_thumbnail',
        ),
    ]
